### ISSUE TITLE
Chrome 上 scroll-behavior: smooth 速度过慢

### ISSUE THREAD

**Issue by ouuan** [Ir1d/oi-wiki-ng#104]

**Comment by CBW2007** [comment]
如果用css的话这个问题貌似无解【摊手】

**Comment by CBW2007** [comment]
CBW2007, [26.04.20 09:42]
其实也还好？

CBW2007, [26.04.20 09:42]
个人觉得不算慢

Xiaodai Dai, [26.04.20 09:42]
比起引入一个新库 我还是觉得动画保持现状可以接受

Xiaodai Dai, [26.04.20 09:43]
毕竟也没有到不可接受的分上

**Comment by ouuan** [comment]
不要动画是一个解决方案 /fad

**Comment by Enter-tainer** [comment]
@ouuan 或许可以在 chrome 浏览器上禁用动画（？）不知道能不能实现

**Comment by Enter-tainer** [comment]
备忘一下：

可能需要我们来手写一个逐帧的动画器

**Comment by Enter-tainer** [comment]
fixed
