### ISSUE TITLE
优化已选中 tab 的样式

### ISSUE THREAD

**Issue by ChungZH** [Ir1d/oi-wiki-ng#56]
![image](https://user-images.githubusercontent.com/42088872/78653399-a3e16600-78f5-11ea-9425-15acbec10d4a.png)
Me

**Comment by diauweb** [comment]
What is the expected behavior?

**Comment by ChungZH** [comment]
I think it should be thicker...

**Comment by diauweb** [comment]
c9f96061983bc5ba00ff0cdd065495051ea25c65
