### ISSUE TITLE
tabs 的点击动画和下划线动画在视觉上有些冲突

### ISSUE THREAD

**Issue by ouuan** [Ir1d/oi-wiki-ng#71]
切换标签页时同时有点击按钮的动画 ![image](https://user-images.githubusercontent.com/30581822/78966938-b3e68900-7b33-11ea-8e48-c25901a21b5f.png)
 与切换标签页的动画 
![image](https://user-images.githubusercontent.com/30581822/78966984-c82a8600-7b33-11ea-8527-0eeb8344bd1f.png)。

这两个动画同时进行，一个在点击处发生，一个从远处开始，在视觉上会使人有点找不到焦点。

我的建议是选择下面两种方案其一：

1. 去掉点击按钮的动画。
2. 用其它方式（如 tab 的字体，像主站那样）表示当前标签页，不给这个新的方式添加切换动画，或者使用不与点击按钮动画冲突的动画。

**Comment by diauweb** [comment]
@ouuan 整了一个无ripple的版本 可以对比下 http://ng.akioi.icu

**Comment by Enter-tainer** [comment]
@diauweb 在发生页面跳转时，indicater 并不会移到它应该在的位置。是否考虑隐藏 indicaer，并启用 ripple 动画效果

**Comment by diauweb** [comment]
> @diauweb 在发生页面跳转时，indicater 并不会移到它应该在的位置。不知道怎么解决 help wanted

fixed

**Comment by diauweb** [comment]
ripple先不管了 现在可以把修复过的tab合进上游了吗
虽然实现的过于dirty

**Comment by Enter-tainer** [comment]
> 切换标签页时同时有点击按钮的动画 ![image](https://user-images.githubusercontent.com/30581822/78966938-b3e68900-7b33-11ea-8e48-c25901a21b5f.png)
> 与切换标签页的动画
> ![image](https://user-images.githubusercontent.com/30581822/78966984-c82a8600-7b33-11ea-8527-0eeb8344bd1f.png)。
> 
> 这两个动画同时进行，一个在点击处发生，一个从远处开始，在视觉上会使人有点找不到焦点。
> 
> 我的建议是选择下面两种方案其一：
> 
> 1. 去掉点击按钮的动画。
> 2. 用其它方式（如 tab 的字体，像主站那样）表示当前标签页，不给这个新的方式添加切换动画，或者使用不与点击按钮动画冲突的动画。

现在好像成功 fix 了，可以 close 吗
